version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_img
    container_name: backend
    ports:
      - 80:80
    volumes:
      - ./src:/app
      - exclusive-backend:/app/node_modules
    env_file:
      - ./.env
    networks:
      - backend_network
    command: npm run ${1:-start}
networks:
  backend_network:
volumes:
  exclusive-backend: